site_name:        POMDPs.jl
repo_url:         https://github.com/JuliaPOMDP/POMDPs.jl 
site_description: API for solving partially observable Markov decision processes in Julia.
site_author:      Maxim Egorov

theme: readthedocs

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - extra
  - tables
  - fenced_code
  #- mdx_math

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- About: index.md
- Installation: install.md
- Getting Started: get_started.md
- Concepts and Architecture: concepts.md
- Defining a POMDP: def_pomdp.md
- Defining a Solver: def_solver.md
- API: api.md
- Frequently Asked Questions: faq.md

